forms.ts: Explicit type to fix local compilation issue
I used to have this issue:
test/fixtures/projects/forms.ts:29:39 - error TS2345: Argument of type 'EventTarget' is not assignable to parameter of type 'HTMLFormElement'.
  Type 'EventTarget' is missing the following properties from type 'HTMLFormElement': acceptCharset, action, autocomplete, elements, and 330 more.

29       isFilled.set(forms.isFormFilled(form, ["sky-*", "meaning"]));
                                         ~~~~

test/fixtures/projects/forms.ts:30:50 - error TS2345: Argument of type 'EventTarget' is not assignable to parameter of type 'HTMLFormElement'.
  Type 'EventTarget' is missing the following properties from type 'HTMLFormElement': acceptCharset, action, autocomplete, elements, and 330 more.

30       formValue.set(JSON.stringify(formDataToObj(form), null, 2));
                                                    ~~~~

Not sure why this compilation issue appeared, and why only on my
machine, but the fix does not bring harm…