Dependency Upgrade bump Express from 4.20.0 to 4.21.2 (#1389)
## Context

Follow-up of #1368 

`Express` 4.2.0 have some known dependency vulnerabilities.
This PR addresses it.

## Proposed solution

### Bump [express](https://github.com/expressjs/express) from 4.20.0 to
4.21.2

- [Releases](https://github.com/expressjs/express/releases)
- [Commits](https://github.com/expressjs/express/compare/4.2.0...4.21.2)

### Fix /boot/key route

A routing fix for /boot was necessary to workaround new version of
path-to-regex

Previous route handling for `/boot/KEY` was crashing after express
update
```javascript
SyntaxError: Invalid regular expression: /^/boot(/(?:(?:((?:(?!/|/boot(/).)+?))/?)?)?$/?$/i: Unterminated group
    at new RegExp (<anonymous>)
    at pathToRegexp (/home/hexa/Programmation/DINUM/grist-core/node_modules/path-to-regexp/index.js:155:10)
    at new Layer (/home/hexa/Programmation/DINUM/grist-core/node_modules/express/lib/router/layer.js:45:17)
    at Function.route (/home/hexa/Programmation/DINUM/grist-core/node_modules/express/lib/router/index.js:505:15)
    at app.<computed> [as get] (/home/hexa/Programmation/DINUM/grist-core/node_modules/express/lib/application.js:498:30)
    at FlexServer.addBootPage (/home/hexa/Programmation/DINUM/grist-core/_build/app/server/lib/FlexServer.js:519:18)
    at MergedServer.create (/home/hexa/Programmation/DINUM/grist-core/_build/app/server/MergedServer.js:91:27)
    at async main (/home/hexa/Programmation/DINUM/grist-core/_build/stubs/app/server/server.js:137:26)
```
So it has been simplified to perform the same with less syntactic
complexity.

```diff
- '/boot(/(:bootKey/?)?)?$'
+ '/boot(/*)?'
```

## Has this been tested?

- [x] 👍 yes, with this PR CI

---------

Co-authored-by: Florent <florent.git@zeteo.me>