(core) [grist-saas] move from browserify to vercel/nft for file collection
Summary:
Preparing the SaaS image has been on shaky ground for years, since
a dependency for file collection has been unmaintained. This shifts
to a maintained package that serves essentially the same purpose,
and removes some workarounds. Dependency on `collect-js-deps` is
dropped for this purpose. It still lingers in lambda upload machinery
via `aws-lambda-upload`.

There was one problem. Adding `@vercel/nft` to devDependencies
changes yarn's hoisting of the `util` npm package. Previously,
the `util` package is `0.10.4`, which worked well. After this
change, `util` wanted to become `0.12.5` which has `support/types.js`
which pulls in `is-arguments` → `call-bind` → `get-intrinsic`, and
`get-intrinsic` v1.3.0 doesn't work correctly when bundled by webpack
for the browser, causing `Uncaught TypeError: GetIntrinsic is not a function`.

The workaround for this was to pin `util` to `0.10.4`. An alternative would
be to eliminate the client-side `util` dependency entirely (the only use
is `util.inspect(obj, {depth: 1})` in `core/app/client/lib/dispose.js`
for error reporting) and add `'util': false` to webpack's `resolve.fallback`.
I couldn't really judge how important the use was, or if there are
reasonable alternatives, so went with pinning to preserve existing
behavior.

The output files seem to work. Tested manually via `server.sh 9999`
in `dist/server.dev`. We may find missing material once this gets
far enough for full deployment tests, but adding material should be
straightforward. And we can now move from `node14` to `node22`.

Test Plan: manual, deployment tests

Reviewers: Spoffy, dsagal

Reviewed By: dsagal

Subscribers: dsagal

Differential Revision: https://phab.getgrist.com/D4875